export const portfolio = {
  name: 'Renke Brixel',
  location: 'Hamburg, Germany',
  emailEncoded: 'cmVua2UuYnJpeGVsK3BvcnRmb2xpb0BnbWFpbC5jb20=',
  github: 'https://github.com/ReynkeDeVos',
  linkedin: 'https://www.linkedin.com/in/rbrixel/',
  portrait: {
    src: '/images/renke-portrait.avif',
    alt: { en: 'Portrait of Renke Brixel', de: 'Porträt von Renke Brixel' },
    width: 480,
    height: 480,
  },
  fullPortrait: {
    src: '/images/renke-full-portrait.avif',
    alt: {
      en: 'Renke Brixel standing with a laptop',
      de: 'Renke Brixel mit einem Laptop',
    },
    width: 720,
    height: 1080,
  },
  identity: {
    en: 'Software developer in Hamburg, Germany',
    de: 'Softwareentwickler in Hamburg, Deutschland',
  },
  introduction: {
    en: 'I build web applications, game mods and tools for the terminal and Linux desktop.',
    de: 'Ich entwickle Webanwendungen, Spiele-Mods und Werkzeuge für Terminal und Linux-Desktop.',
  },
  interests: [
    {
      id: 'exploration',
      title: { en: 'Curious by default', de: 'Neugierig auf Neues' },
      description: {
        en: 'I enjoy trying new technologies and finding out where they help in real projects. This portfolio is one of them.',
        de: 'Ich probiere gern neue Technologien aus und finde heraus, wo sie in echten Projekten helfen. Dieses Portfolio ist eines davon.',
      },
    },
    {
      id: 'terminal',
      title: { en: 'Terminal first', de: 'Terminal zuerst' },
      description: {
        en: 'I love a terminal-first workflow and Arch Linux. Linux has been part of my life for more than 20 years.',
        de: 'Ich liebe einen terminalbasierten Workflow und Arch Linux. Linux begleitet mich seit mehr als 20 Jahren.',
      },
    },
    {
      id: 'ai',
      title: { en: 'AI with a purpose', de: 'KI mit einem Zweck' },
      description: {
        en: 'I follow AI news daily and evaluate which tools actually help me build, investigate and review software. I participated in the Claude Code for Business course as part of our company’s preparation for the business partner program.',
        de: 'Ich verfolge täglich KI-Nachrichten und prüfe, welche Werkzeuge mir beim Entwickeln, Untersuchen und Prüfen von Software wirklich helfen. Ich habe am Kurs Claude Code for Business teilgenommen, um unser Unternehmen auf das Business-Partnerprogramm vorzubereiten.',
      },
    },
  ],
  coreStrengths: [
    { en: 'React & TypeScript', de: 'React & TypeScript' },
    { en: 'C#/.NET & Python', de: 'C#/.NET & Python' },
    { en: 'Linux & terminal tools', de: 'Linux & Terminal-Werkzeuge' },
    { en: 'Ultrarunning', de: 'Ultralaufen' },
  ],
  skills: [
    {
      id: 'languages',
      title: { en: 'Languages & foundations', de: 'Sprachen & Grundlagen' },
      technologies: ['TypeScript', 'JavaScript', 'Python', 'C#', 'SQL', 'HTML', 'CSS', 'zsh'],
      description: {
        en: 'Algorithms, data structures, object-oriented design and asynchronous programming are part of my teaching and development work.',
        de: 'Algorithmen, Datenstrukturen, objektorientiertes Design und asynchrone Programmierung gehören zu meiner Lehr- und Entwicklungsarbeit.',
      },
    },
    {
      id: 'web',
      title: { en: 'Web interfaces', de: 'Weboberflächen' },
      technologies: [
        'React',
        'Next.js',
        'TanStack Start',
        'React Router',
        'TanStack Query',
        'Tailwind CSS',
        'shadcn/ui',
        'Zod',
        'Effect',
      ],
      description: {
        en: 'Interfaces, routing, server rendering, state and data validation. TanStack Start and shadcn/ui are part of this portfolio’s stack.',
        de: 'Oberflächen, Routing, Server-Rendering, Zustandsverwaltung und Datenvalidierung. TanStack Start und shadcn/ui gehören zum Stack dieses Portfolios.',
      },
    },
    {
      id: 'backend',
      title: { en: 'APIs & data', de: 'APIs & Daten' },
      technologies: [
        'ASP.NET Core',
        'Entity Framework Core',
        'Node.js',
        'Express',
        'Flask',
        'PostgreSQL',
        'MongoDB',
        'Mongoose',
        'SQLite',
        'REST',
        'OpenAPI',
        'Better Auth',
      ],
      description: {
        en: 'API design, persistence and authentication with custom JWT/cookie solutions, ASP.NET Core Identity and Better Auth.',
        de: 'API-Design, Persistenz und Authentifizierung mit eigenen JWT-/Cookie-Lösungen, ASP.NET Core Identity und Better Auth.',
      },
    },
    {
      id: 'quality',
      title: { en: 'Quality & delivery', de: 'Qualität & Bereitstellung' },
      technologies: [
        'Vitest',
        'Testing Library',
        'pytest',
        'GitHub Actions',
        'Docker',
        'Podman',
        'Azure',
        'Git',
        'Oxc',
        'Fallow',
        'Cloudflare',
        'Render',
        'Vercel',
        'Railway',
      ],
      description: {
        en: 'I write unit and integration tests, use Docker and Podman, and deploy applications to Cloudflare, Render, Vercel or Railway.',
        de: 'Ich schreibe Unit- und Integrationstests, nutze Docker und Podman und veröffentliche Anwendungen auf Cloudflare, Render, Vercel oder Railway.',
      },
    },
    {
      id: 'ai-tools',
      title: { en: 'AI & automation', de: 'KI & Automatisierung' },
      technologies: [
        'OpenAI SDK',
        'OpenAI Agents SDK',
        'Anthropic SDK',
        'MCP',
        'n8n',
        'Claude Code',
        'Codex',
        'pi',
      ],
      description: {
        en: 'Teaching examples and experiments with streaming, tool calls, agent handoffs and guardrails, alongside Claude Code workflows.',
        de: 'Lehrbeispiele und Experimente mit Streaming, Tool-Aufrufen, Agenten-Übergaben und Guardrails sowie Claude-Code-Workflows.',
      },
    },
  ],
  aiRecommendations: {
    updated: '2026-10-01',
    introduction: {
      en: 'Thinking levels are settings to try, not a promise of better results.',
      de: 'Denkstufen sind Einstellungen zum Ausprobieren, kein Versprechen für bessere Ergebnisse.',
    },
    items: [
      {
        task: { en: 'Build & implement', de: 'Entwickeln & umsetzen' },
        model: 'Opus 5.5',
        effort: 'Medium',
        note: { en: 'High for complex work', de: 'High für komplexe Aufgaben' },
      },
      {
        task: { en: 'Investigate & debug', de: 'Untersuchen & debuggen' },
        model: 'GPT-6.1 Sol',
        effort: 'Medium',
        note: { en: 'High for difficult diagnosis', de: 'High für schwierige Diagnosen' },
      },
      {
        task: { en: 'Review code', de: 'Code prüfen' },
        model: 'GPT-6.1 Sol',
        effort: 'High',
        note: { en: 'Independent review', de: 'Unabhängige Prüfung' },
      },
      {
        task: { en: 'Explore visual design', de: 'Visuelles Design erkunden' },
        model: 'Opus 5.5',
        effort: 'Medium',
        note: { en: 'Layout and visual refinements', de: 'Layout und visuelle Verfeinerung' },
      },
    ],
  },
  portfolioBuild: {
    introduction: {
      en: 'A React app with two prerendered locales.',
      de: 'Eine React-App mit zwei vorgerenderten Sprachfassungen.',
    },
    items: [
      {
        id: 'rendering',
        topic: { en: 'Rendering', de: 'Rendering' },
        technologies: ['TanStack Start', 'React 19', 'TypeScript 7', 'Vite 8'],
        description: {
          en: 'TanStack Start prerenders / and /de to static HTML, then React hydrates the controls. All four panels render upfront and router code splitting is off, so tab changes need no route change or fetch. The tradeoff: initial HTML and client bundle include every panel.',
          de: 'TanStack Start rendert / und /de vorab als statisches HTML, danach hydratisiert React die Bedienelemente. Alle vier Bereiche werden vorab gerendert und Router-Code-Splitting ist deaktiviert, daher brauchen Tabwechsel weder Routenwechsel noch Datenabruf. Dafür enthalten initiales HTML und Client-Bundle jeden Bereich.',
        },
      },
      {
        id: 'interface',
        topic: { en: 'Interaction', de: 'Interaktion' },
        technologies: ['Tailwind CSS 4', 'shadcn/ui', 'Radix'],
        description: {
          en: 'Tabs and the portrait dialog are shadcn components kept in the repo and built on Radix, which handles keyboard navigation and focus. Links are native anchors. Tailwind covers layout and states; Material 3 tokens live in custom CSS.',
          de: 'Tabs und Porträt-Dialog sind shadcn-Komponenten im Repository auf Radix-Basis, das Tastaturbedienung und Fokus übernimmt. Links sind native Anker. Tailwind deckt Layout und Zustände ab; Material-3-Tokens sind in eigenem CSS umgesetzt.',
        },
      },
      {
        id: 'design',
        topic: { en: 'Theme & assets', de: 'Theme & Assets' },
        technologies: ['Roboto Flex', 'CSS', 'AVIF'],
        description: {
          en: 'A head script restores the saved theme before first paint; one data-theme attribute on html swaps all color tokens. Transitions use transform and opacity and drop to zero duration under prefers-reduced-motion. The variable WOFF2 font is self-hosted and preloaded; AVIF portraits carry intrinsic dimensions.',
          de: 'Ein Head-Skript stellt das gespeicherte Farbschema vor der ersten Darstellung wieder her; ein data-theme-Attribut am html-Element tauscht alle Farb-Tokens. Übergänge nutzen transform und opacity und laufen bei prefers-reduced-motion ohne Dauer. Die variable WOFF2-Schrift ist selbst gehostet und vorgeladen; AVIF-Porträts haben intrinsische Abmessungen.',
        },
      },
      {
        id: 'content',
        topic: { en: 'Content', de: 'Inhalte' },
        technologies: ['Zod'],
        description: {
          en: 'Copy lives in English and German TypeScript dictionaries, with no CMS or runtime API. A build script checks required fields, URLs and dates with Zod. The validator stays outside the client import graph.',
          de: 'Die Texte liegen in englischen und deutschen TypeScript-Dictionaries, ohne CMS oder Laufzeit-API. Ein Build-Skript prüft Pflichtfelder, URLs und Datumsangaben mit Zod. Die Validierung bleibt außerhalb des Client-Importgraphen.',
        },
      },
      {
        id: 'tooling',
        topic: { en: 'Toolchain', de: 'Toolchain' },
        technologies: ['mise', 'Node.js', 'aube', 'Oxlint', 'Oxfmt'],
        description: {
          en: 'I use mise to select Node LTS for development and builds, and aube to manage dependencies and the lockfile. I run project scripts with aubr, check the code with type-aware Oxlint rules and format it with Oxfmt.',
          de: 'Für Entwicklung und Builds wähle ich mit mise Node LTS aus. Mit aube verwalte ich Abhängigkeiten und Lockfile und mit aubr starte ich die Projektskripte. Ich prüfe den Code mit typbasierten Oxlint-Regeln und formatiere ihn mit Oxfmt.',
        },
      },
      {
        id: 'hosting',
        topic: { en: 'Deployment', de: 'Deployment' },
        technologies: ['Cloudflare Workers'],
        description: {
          en: 'Configured for Cloudflare Workers through the Cloudflare Vite plugin, with workerd running the server build; not publicly deployed. _headers caches hashed /assets files as immutable for one year and /images for one day.',
          de: 'Über das Cloudflare-Vite-Plugin für Cloudflare Workers eingerichtet, workerd führt den Server-Build aus; nicht öffentlich bereitgestellt. _headers cacht gehashte Dateien unter /assets ein Jahr lang als immutable und /images einen Tag.',
        },
      },
    ],
    links: [
      { name: 'TanStack Start', url: 'https://tanstack.com/start/latest' },
      { name: 'React 19', url: 'https://react.dev/' },
      { name: 'TypeScript 7', url: 'https://www.typescriptlang.org/docs/' },
      { name: 'Vite 8', url: 'https://vite.dev/guide/' },
      { name: 'Tailwind CSS 4', url: 'https://tailwindcss.com/docs' },
      { name: 'shadcn/ui', url: 'https://ui.shadcn.com/docs' },
      { name: 'Radix', url: 'https://www.radix-ui.com/primitives/docs/overview/introduction' },
      { name: 'Roboto Flex', url: 'https://fontsource.org/fonts/roboto-flex' },
      { name: 'CSS', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS' },
      { name: 'AVIF', url: 'https://aomediacodec.github.io/av1-avif/' },
      { name: 'Zod', url: 'https://zod.dev/' },
      { name: 'mise', url: 'https://mise.jdx.dev/' },
      { name: 'Node.js', url: 'https://nodejs.org/' },
      { name: 'aube', url: 'https://aube.sh/guide.html' },
      { name: 'Oxlint', url: 'https://oxc.rs/docs/guide/usage/linter' },
      { name: 'Oxfmt', url: 'https://oxc.rs/docs/guide/usage/formatter' },
      { name: 'Cloudflare Workers', url: 'https://developers.cloudflare.com/workers/' },
    ],
  },
  teaching: [
    {
      en: 'Frontend development',
      de: 'Frontend-Entwicklung',
      technologies: ['React', 'TypeScript'],
    },
    {
      en: 'Algorithms & data structures',
      de: 'Algorithmen & Datenstrukturen',
      technologies: ['Python'],
    },
    { en: 'Backend development', de: 'Backend-Entwicklung', technologies: ['C#', '.NET'] },
    {
      en: 'React frameworks & data',
      de: 'React-Frameworks & Daten',
      technologies: ['Next.js', 'React Router', 'TanStack Query', 'Zod'],
    },
    {
      en: 'Python web & SQL',
      de: 'Python-Webentwicklung & SQL',
      technologies: ['Flask', 'PostgreSQL'],
    },
    {
      en: 'Node APIs & authentication',
      de: 'Node-APIs & Authentifizierung',
      technologies: ['Node.js', 'Express', 'MongoDB', 'Mongoose', 'JWT', 'Better Auth'],
    },
    {
      en: '.NET APIs & persistence',
      de: '.NET-APIs & Persistenz',
      technologies: ['ASP.NET Core', 'Entity Framework Core', 'ASP.NET Core Identity', 'OpenAPI'],
    },
    {
      en: 'Testing & delivery',
      de: 'Tests & Bereitstellung',
      technologies: ['Vitest', 'Testing Library', 'GitHub Actions', 'Docker', 'Podman', 'Azure'],
    },
    {
      en: 'AI integration & automation',
      de: 'KI-Integration & Automatisierung',
      technologies: [
        'OpenAI SDK',
        'OpenAI Agents SDK',
        'Anthropic SDK',
        'Claude Agent SDK',
        'MCP',
        'n8n',
      ],
    },
  ],
  experience: [
    {
      organization: { en: 'WBS Coding School', de: 'WBS Coding School' },
      url: 'https://www.wbscodingschool.com/',
      period: '2025-present',
      role: { en: 'Software development instructor', de: 'Dozent für Softwareentwicklung' },
    },
    {
      organization: { en: 'Closelink', de: 'Closelink' },
      url: 'https://www.closelink.com/',
      period: '2024',
      role: { en: 'Frontend development intern', de: 'Praktikant Frontend-Entwicklung' },
    },
    {
      organization: { en: 'Leibniz Institute for Virology', de: 'Leibniz-Institut für Virologie' },
      url: 'https://www.leibniz-liv.de/en/research/research-units/virus-host-interaction',
      period: '2014-2023',
      role: { en: 'Biological-technical assistant', de: 'Biologisch-technischer Assistent' },
    },
    {
      organization: {
        en: 'University Medical Center Hamburg-Eppendorf',
        de: 'Universitätsklinikum Hamburg-Eppendorf',
      },
      url: 'https://www.uke.de/kliniken-institute/institute/institut-f%C3%BCr-tumorbiologie/index.html',
      period: '2012-2014',
      role: { en: 'Biological-technical assistant', de: 'Biologisch-technischer Assistent' },
    },
    {
      organization: {
        en: 'University of Utah School of Medicine',
        de: 'University of Utah School of Medicine',
      },
      url: 'https://medicine.utah.edu/',
      period: '2012',
      role: { en: 'Research intern', de: 'Forschungspraktikant' },
    },
  ],
  projects: [
    {
      id: 'reputation-assistant',
      name: 'Reputation Assistant',
      category: { en: 'Add-on for Caves of Qud', de: 'Erweiterung für Caves of Qud' },
      description: {
        en: 'In the role-playing game Caves of Qud, you meet characters who belong to different groups, and each group thinks better or worse of your character. When you take a closer look at someone you meet, this add-on shows how their groups see you and how an action could change that. That helps you decide what to do next.',
        de: 'Im Rollenspiel Caves of Qud begegnet man Figuren, die zu verschiedenen Gruppen gehören. Jede Gruppe ist der eigenen Spielfigur mehr oder weniger wohlgesonnen. Sieht man sich eine Figur genauer an, zeigt die Erweiterung, wie ihre Gruppen zur eigenen Spielfigur stehen und wie eine Handlung das verändern könnte. Das hilft bei der Entscheidung, was man als Nächstes tut.',
      },
      technologies: ['C#', 'Harmony'],
      url: 'https://github.com/ReynkeDeVos/CoQ_MOD_ReputationAssistant',
      details: {
        en: 'Players can choose which groups matter most to them. The default settings follow the reputation guide on qudzoo.',
        de: 'Man kann festlegen, welche Gruppen einem am wichtigsten sind. Die Standardeinstellungen folgen dem Ruf-Leitfaden von qudzoo.',
      },
      featured: true,
    },
    {
      id: 'scoundrel-tui',
      name: 'Scoundrel TUI',
      category: { en: 'Card game for the terminal', de: 'Kartenspiel fürs Terminal' },
      description: {
        en: 'A card game with illustrated cards that runs in the terminal, the text-based workspace on a computer. You play it entirely with the keyboard.',
        de: 'Ein Kartenspiel mit illustrierten Karten. Es läuft im Terminal, dem textbasierten Arbeitsbereich eines Computers, und wird komplett mit der Tastatur gespielt.',
      },
      technologies: ['Python', 'Textual'],
      url: 'https://github.com/ReynkeDeVos/Scoundrel-TUI',
      details: {
        en: 'Based on the card game Scoundrel by Zach Gage and Kurt Bieg. Credits for the game and the artwork are in the repository.',
        de: 'Nach dem Kartenspiel Scoundrel von Zach Gage und Kurt Bieg. Die Nachweise für Spiel und Bilder stehen im Repository.',
      },
      featured: true,
    },
    {
      id: 'omarchy-stats',
      name: 'Omarchy System Stats',
      category: { en: 'Linux desktop add-on', de: 'Erweiterung für den Linux-Desktop' },
      description: {
        en: 'Shows how busy the processor, memory and graphics card are, right on the Linux desktop.',
        de: 'Zeigt direkt auf dem Linux-Desktop, wie stark Prozessor, Arbeitsspeicher und Grafikkarte ausgelastet sind.',
      },
      technologies: ['QML', 'C', 'Quickshell', 'Linux'],
      url: 'https://github.com/ReynkeDeVos/omarchy-plugin-system-stats',
      details: {
        en: 'If a computer does not provide one of these values, the display says so.',
        de: 'Liefert ein Rechner einen dieser Werte nicht, zeigt die Anzeige das an.',
      },
      featured: false,
    },
    {
      id: 'name-shuffler',
      name: 'Name Shuffler CLI',
      category: { en: 'Terminal tool', de: 'Terminal-Werkzeug' },
      description: {
        en: 'Enter a list of names and choose how many groups you need. The tool randomly assigns people to those groups, directly in the terminal.',
        de: 'Namen eingeben und die gewünschte Anzahl an Gruppen wählen. Das Werkzeug verteilt die Personen per Zufall auf diese Gruppen, direkt im Terminal.',
      },
      technologies: ['JavaScript', 'Node.js', 'Inquirer'],
      url: 'https://github.com/ReynkeDeVos/name-shuffler-cli',
      details: {
        en: 'An experiment in AI-assisted development with Claude.',
        de: 'Ein Experiment mit KI-gestützter Entwicklung und Claude.',
      },
      featured: false,
    },
    {
      id: 'elder-gym-bro',
      name: 'Elder Gym Bro App',
      category: { en: 'Team project', de: 'Teamprojekt' },
      description: {
        en: 'A fitness app for planning workouts and following your progress.',
        de: 'Eine Fitness-App, mit der man Trainings plant und die eigenen Fortschritte verfolgt.',
      },
      technologies: ['React', 'Tailwind CSS', 'Node.js', 'Express'],
      url: 'https://github.com/ReynkeDeVos/ElderGymBroApp',
      details: {
        en: 'A final project by a team of four: Michal, Sebastian, Alex and Renke.',
        de: 'Ein Abschlussprojekt im Viererteam mit Michal, Sebastian, Alex und Renke.',
      },
      featured: false,
    },
    {
      id: 'pokemon-battle',
      name: 'PokémonBattle',
      category: { en: 'Collaborative fork', de: 'Gemeinschaftlicher Fork' },
      description: {
        en: 'A browser game in which Pokémon creatures fight each other.',
        de: 'Ein Browserspiel, in dem Pokémon-Figuren gegeneinander kämpfen.',
      },
      technologies: ['React', 'Context API', 'CSS'],
      url: 'https://github.com/ReynkeDeVos/PokemonBattle',
      details: {
        en: 'A fork of EinKinddesWindes/PokemonBattle.',
        de: 'Ein Fork von EinKinddesWindes/PokemonBattle.',
      },
      featured: true,
    },
  ],
};
