# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools==4.66.1", "brotli==1.2.0"]
# ///
"""Subset both variable fonts from the complete local source corpus."""

import html
import re
import unicodedata
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE_EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".css", ".json", ".html"}
FONTS = (
    ("roboto-flex", "Roboto Flex Variable"),
    ("google-sans-flex", "Google Sans Flex Variable"),
)
GENERATED = ROOT / "src/generated/fonts"
# Printable ASCII covers Intl dates, numeric values and the decoded email.
# Keep German letters even when a particular spelling isn't currently in use.
BASE_TEXT = "".join(chr(code) for code in range(0x20, 0x7F)) + "ÄÖÜäöüßẞ\u00a0"
JS_ESCAPE = re.compile(
    r"\\(?:u\{([0-9a-fA-F]{1,6})\}|u([0-9a-fA-F]{4})|x([0-9a-fA-F]{2}))"
)
CSS_ESCAPE = re.compile(r"\\([0-9a-fA-F]{1,6})(?:\s)?")


def source_characters(source: Path) -> set[int]:
    """Include every state and locale, without executing application code."""
    texts = [BASE_TEXT]
    for path in sorted(source.rglob("*")):
        if not path.is_file() or path.suffix not in SOURCE_EXTENSIONS:
            continue
        if (
            "generated" in path.relative_to(source).parts
            or path.name == "routeTree.gen.ts"
        ):
            continue
        text = path.read_text(encoding="utf-8")
        texts.append(text)
        # Decode entities and escapes as well as keeping their literal source.
        # This is conservative: comments and identifiers may retain a few extra glyphs.
        text = html.unescape(text)
        if path.suffix == ".css":
            text = CSS_ESCAPE.sub(lambda match: chr(int(match[1], 16)), text)
        else:
            text = JS_ESCAPE.sub(
                lambda match: chr(
                    int(next(value for value in match.groups() if value), 16)
                ),
                text,
            )
        texts.append(text)
    corpus = "".join(texts)
    # Cover both spellings of accented letters and CSS casing transformations.
    corpus += corpus.upper() + corpus.lower()
    corpus += unicodedata.normalize("NFC", corpus) + unicodedata.normalize(
        "NFD", corpus
    )
    return {ord(character) for character in corpus}


def unicode_range(codepoints: set[int]) -> str:
    ranges = []
    ordered = sorted(codepoints)
    start = end = ordered[0]
    for codepoint in ordered[1:]:
        if codepoint == end + 1:
            end = codepoint
        else:
            ranges.append(
                f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}"
            )
            start = end = codepoint
    ranges.append(f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}")
    return ", ".join(ranges)


def subset_font(source: Path, destination: Path, codepoints: set[int]) -> set[int]:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]  # Preserve attribution, licenses and variable-axis names.
    options.recalc_timestamp = False
    options.harfbuzz_repacker = False  # Reproducible without optional native packages.
    with TTFont(source, recalcTimestamp=False) as font:
        supported = set(font.getBestCmap()) & codepoints
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=supported)
        subsetter.subset(font)
        font.save(destination)
    # Read the WOFF2 back: a build must not ship a corrupt or incomplete subset.
    with TTFont(destination) as generated:
        if not supported <= set(generated.getBestCmap()):
            raise ValueError(f"Missing characters in {destination}")
    return supported


def build_fonts() -> None:
    codepoints = source_characters(ROOT / "src")
    GENERATED.mkdir(parents=True, exist_ok=True)
    faces = ["/* Generated by scripts/subset-fonts.py; do not edit. */\n"]
    for slug, family in FONTS:
        package = ROOT / "node_modules/@fontsource-variable" / slug
        source = package / "files" / f"{slug}-latin-wght-normal.woff2"
        filename = f"{slug}-subset.woff2"
        destination = GENERATED / filename
        supported = subset_font(source, destination, codepoints)
        with TTFont(source) as font:
            axis = next(axis for axis in font["fvar"].axes if axis.axisTag == "wght")
            weight = f"{axis.minValue:g} {axis.maxValue:g}"
        faces.append(
            f"@font-face {{\n"
            f"  font-family: '{family}';\n"
            f"  font-style: normal;\n"
            f"  font-display: swap;\n"
            f"  font-weight: {weight};\n"
            f"  src: url('./{filename}') format('woff2');\n"
            f"  unicode-range: {unicode_range(supported)};\n"
            f"}}\n"
        )
        # Include the upstream license alongside the fonts in the served assets.
        licenses = ROOT / "public/fonts"
        licenses.mkdir(parents=True, exist_ok=True)
        (licenses / f"{slug}-LICENSE.txt").write_bytes(
            (package / "LICENSE").read_bytes()
        )
        before, after = source.stat().st_size, destination.stat().st_size
        print(
            f"{slug}: {before:,} → {after:,} bytes ({1 - after / before:.1%} smaller), {len(supported)} characters"
        )
    (GENERATED / "fonts.css").write_text("\n".join(faces), encoding="utf-8")


if __name__ == "__main__":
    build_fonts()
